version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      IMAGE_NAME: godot
      CONTAINER_NAME: godot
    steps:
      - checkout
      - run:
          name: Build dockerfile
          command: docker build -t "${IMAGE_NAME}" .
      - run:
          name: Get godot demo projects
          command: |
            git clone \
              --depth 1 \
              --branch 3.2-5bd2bbf \
              https://github.com/godotengine/godot-demo-projects.git
      = run:
          name: create export presets
          command: |
            curl https://raw.githubusercontent.com/mtlynch/godot-ci-scratch/4e6d1c72e2ee18da295ee5440524b25c010e9cba/export_presets.cfg \
              -o 2d/pong/export_presets.cfg
      - run:
          name: Export an app using the container
          command: |
            docker run \
              --volume "${PWD}/godot-demo-projects/2d/pong:/app" \
              --name "${CONTAINER_NAME}" \
              "${IMAGE_NAME}" \
                --export HTML5 /app/project.godot /tmp/index.html
workflows:
  version: 2
  all-tests:
    jobs:
      - build
