version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      IMAGE_NAME: godot
      CONTAINER_NAME: godot
    steps:
      - checkout
      - run:
          name: Build dockerfile
          command: docker build -t "${IMAGE_NAME}" .
      - run:
          name: Run a container
          command: docker run --name "${CONTAINER_NAME}" "${IMAGE_NAME}" --version
workflows:
  version: 2
  all-tests:
    jobs:
      - build
